# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  testProject: ./AzureDevOpsTest/AzureDevOpsTest.csproj
  applicationProject: ./AzureDevOpsApp/AzureDevOpsApp.csproj

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: sdk

- script: |
    echo "Restrieving external libraries..."
    dotnet restore
  displayName: 'Resolve Dependencies'

- script: |
    echo "Building projects..."
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Source'

- script: |
    echo "Running tests...""
    dotnet test $(testProject)
  displayName: 'Execute Tests'

- script: |
    echo "Creating final application package..."
    dotnet publish $(applicationProject) -o ./publish --configuration $(buildConfiguration)
  displayName: 'Final Application Package'
